name: Test for skillfactory
on:
  push:
    branches: [ main ]
    paths:
      - '**.sql'
      
jobs:
  SQL-script:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        ports:
          - 4497:4497
        env:
          MYSQL_DATABASE: Rfam
          
    steps:
      - uses: actions/checkout@v3
      - name: Start sql
        run: mysql --user rfamro --host mysql-rfam-public.ebi.ac.uk --port 4497 --database Rfam
      - name: run script
     (Вот тут не ясно, как вызвать скрипт)
                     
                                                      
      
